### ISSUE TITLE
why do u use R2DBC 

### ISSUE THREAD

**Issue by fizz12344321** [DevProblems/spring-for-graphql-r2dbc#1]
Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

**Comment by DevProblems** [comment]
The project focussed on showing the spring way(annotation based) of implementing the graphql and not on the db driver. So the driver is not much of a concern.

**Comment by DevProblems** [comment]
> Hi, i am reading your project and i am interested in this, but i have a question, why do you use R2DBC instead of other non blocking IO like Hibernate Reactive or others... can you tell me your purpose, the pros and cons of R2DBC, thank you so much

The project focussed on showing the spring way(annotation based) of implementing the graphql and not on the db driver. So the driver is not much of a concern.
